service: video-preview-generator
frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: us-west-2
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

plugins:
  - serverless-python-requirements
functions:
  video-preview-generator:
    name: ${sls:stage}-video-preview-generator
    handler: index.main
    layers:
      - Ref: PythonRequirementsLambdaLayer
    memorySize: 2048
    timeout: 120
    architecture: x86_64
    package:
      patterns:
      - index.py
      - '!node_modules/**'
      - '!package.json'
      - '!package-lock.json'
      - '!requirements.txt'
    

custom:
  bucket: ${env:BUCKET, 'honeycomb-video-preview-us-west-2'}
  pythonRequirements:
    dockerizePip: true
    layer: 
      name: video-preview-generator
      description: "Layer which contains moviepy library"
      compatibleRuntimes:
        - python3.8
      compatibleArchitectures:
        - x86_64
      package:
        exclude:
          - "*/boto3/examples/*"
          # NOTE: commented out services are INCLUDED
          - "*/botocore/data/accessanalyzer/*"
          - "*/botocore/data/acm/*"
          - "*/botocore/data/acm-pca/*"
          - "*/botocore/data/alexaforbusiness/*"
          - "*/botocore/data/amplify/*"
          - '*/botocore/data/apigateway/*'
          - "*/botocore/data/apigatewaymanagementapi/*"
          - '*/botocore/data/apigatewayv2/*'
          - "*/botocore/data/appconfig/*"
          - "*/botocore/data/application-autoscaling/*"
          - "*/botocore/data/application-insights/*"
          - "*/botocore/data/appmesh/*"
          - "*/botocore/data/appstream/*"
          - "*/botocore/data/appsync/*"
          - "*/botocore/data/athena/*"
          - "*/botocore/data/autoscaling/*"
          - "*/botocore/data/autoscaling-plans/*"
          - "*/botocore/data/backup/*"
          - "*/botocore/data/batch/*"
          - "*/botocore/data/budgets/*"
          - "*/botocore/data/ce/*"
          - "*/botocore/data/chime/*"
          - "*/botocore/data/cloud9/*"
          - "*/botocore/data/clouddirectory/*"
          - "*/botocore/data/cloudformation/*"
          - "*/botocore/data/cloudfront/*"
          - "*/botocore/data/cloudhsm/*"
          - "*/botocore/data/cloudhsmv2/*"
          - "*/botocore/data/cloudsearch/*"
          - "*/botocore/data/cloudsearchdomain/*"
          - "*/botocore/data/cloudtrail/*"
          - "*/botocore/data/cloudwatch/*"
          - "*/botocore/data/codebuild/*"
          - "*/botocore/data/codecommit/*"
          - "*/botocore/data/codedeploy/*"
          - "*/botocore/data/codeguruprofiler/*"
          - "*/botocore/data/codeguru-reviewer/*"
          - "*/botocore/data/codepipeline/*"
          - "*/botocore/data/codestar/*"
          - "*/botocore/data/codestar-connections/*"
          - "*/botocore/data/codestar-notifications/*"
          - "*/botocore/data/cognito-identity/*"
          - "*/botocore/data/cognito-idp/*"
          - "*/botocore/data/cognito-sync/*"
          - "*/botocore/data/comprehend/*"
          - "*/botocore/data/comprehendmedical/*"
          - "*/botocore/data/compute-optimizer/*"
          - '*/botocore/data/config/*'
          - "*/botocore/data/connect/*"
          - "*/botocore/data/connectparticipant/*"
          - "*/botocore/data/cur/*"
          - "*/botocore/data/dataexchange/*"
          - "*/botocore/data/datapipeline/*"
          - "*/botocore/data/datasync/*"
          - "*/botocore/data/dax/*"
          - "*/botocore/data/detective/*"
          - "*/botocore/data/devicefarm/*"
          - "*/botocore/data/directconnect/*"
          - "*/botocore/data/discovery/*"
          - "*/botocore/data/dlm/*"
          - "*/botocore/data/dms/*"
          - "*/botocore/data/docdb/*"
          - "*/botocore/data/ds/*"
          - "*/botocore/data/dynamodb/*"
          - "*/botocore/data/dynamodbstreams/*"
          - "*/botocore/data/ebs/*"
          - '*/botocore/data/ec2/*'
          - '*/botocore/data/ec2-instance-connect/*'
          - "*/botocore/data/ecr/*"
          - "*/botocore/data/ecs/*"
          - "*/botocore/data/efs/*"
          - "*/botocore/data/eks/*"
          - "*/botocore/data/elasticache/*"
          - "*/botocore/data/elasticbeanstalk/*"
          - "*/botocore/data/elastic-inference/*"
          - "*/botocore/data/elastictranscoder/*"
          - "*/botocore/data/elb/*"
          - "*/botocore/data/elbv2/*"
          - "*/botocore/data/emr/*"
          - "*/botocore/data/es/*"
          - "*/botocore//data/events/*"
          - "*/botocore/data/firehose/*"
          - "*/botocore/data/fms/*"
          - "*/botocore/data/forecast/*"
          - "*/botocore/data/forecastquery/*"
          - "*/botocore/data/frauddetector/*"
          - "*/botocore/data/fsx/*"
          - "*/botocore/data/gamelift/*"
          - "*/botocore/data/glacier/*"
          - "*/botocore/data/globalaccelerator/*"
          - "*/botocore/data/glue/*"
          - "*/botocore/data/greengrass/*"
          - "*/botocore/data/groundstation/*"
          - "*/botocore/data/guardduty/*"
          - "*/botocore/data/health/*"
          - '*/botocore/data/iam/*'
          - "*/botocore/data/imagebuilder/*"
          - "*/botocore/data/importexport/*"
          - "*/botocore/data/inspector/*"
          - "*/botocore/data/iot/*"
          - "*/botocore/data/iot1click-devices/*"
          - "*/botocore/data/iot1click-projects/*"
          - "*/botocore/data/iotanalytics/*"
          - "*/botocore/data/iot-data/*"
          - "*/botocore/data/iotevents/*"
          - "*/botocore/data/iotevents-data/*"
          - "*/botocore/data/iot-jobs-data/*"
          - "*/botocore/data/iotsecuretunneling/*"
          - "*/botocore/data/iotthingsgraph/*"
          - "*/botocore/data/kafka/*"
          - "*/botocore/data/kendra/*"
          - "*/botocore/data/kinesis/*"
          - "*/botocore/data/kinesisanalytics/*"
          - "*/botocore/data/kinesisanalyticsv2/*"
          - "*/botocore/data/kinesisvideo/*"
          - "*/botocore/data/kinesis-video-archived-media/*"
          - "*/botocore/data/kinesis-video-media/*"
          - "*/botocore/data/kinesis-video-signaling/*"
          - "*/botocore/data/kms/*"
          - "*/botocore/data/lakeformation/*"
          - '*/botocore/data/lambda/*'
          - "*/botocore/data/lex-models/*"
          - "*/botocore/data/lex-runtime/*"
          - "*/botocore/data/license-manager/*"
          - "*/botocore/data/lightsail/*"
          - '*/botocore/data/logs/*'
          - "*/botocore/data/machinelearning/*"
          - "*/botocore/data/macie/*"
          - "*/botocore/data/managedblockchain/*"
          - "*/botocore/data/marketplace-catalog/*"
          - "*/botocore/data/marketplacecommerceanalytics/*"
          - "*/botocore/data/marketplace-entitlement/*"
          - "*/botocore/data/mediaconnect/*"
          - "*/botocore/data/mediaconvert/*"
          - "*/botocore/data/medialive/*"
          - "*/botocore/data/mediapackage/*"
          - "*/botocore/data/mediapackage-vod/*"
          - "*/botocore/data/mediastore/*"
          - "*/botocore/data/mediastore-data/*"
          - "*/botocore/data/mediatailor/*"
          - "*/botocore/data/meteringmarketplace/*"
          - "*/botocore/data/mgh/*"
          - "*/botocore/data/migrationhub-config/*"
          - "*/botocore/data/mobile/*"
          - "*/botocore/data/mq/*"
          - "*/botocore/data/mturk/*"
          - "*/botocore/data/neptune/*"
          - "*/botocore/data/networkmanager/*"
          - "*/botocore/data/opsworks/*"
          - "*/botocore/data/opsworkscm/*"
          - "*/botocore/data/organizations/*"
          - "*/botocore/data/outposts/*"
          - "*/botocore/data/personalize/*"
          - "*/botocore/data/personalize-events/*"
          - "*/botocore/data/personalize-runtime/*"
          - "*/botocore/data/pi/*"
          - "*/botocore/data/pinpoint/*"
          - "*/botocore/data/pinpoint-email/*"
          - "*/botocore/data/pinpoint-sms-voice/*"
          - "*/botocore/data/polly/*"
          - "*/botocore/data/pricing/*"
          - "*/botocore/data/qldb/*"
          - "*/botocore/data/qldb-session/*"
          - "*/botocore/data/quicksight/*"
          - "*/botocore/data/ram/*"
          - "*/botocore/data/rds/*"
          - "*/botocore/data/rds-data/*"
          - "*/botocore/data/redshift/*"
          - "*/botocore/data/rekognition/*"
          - "*/botocore/data/resource-groups/*"
          - "*/botocore/data/resourcegroupstaggingapi/*"
          - "*/botocore/data/robomaker/*"
          - "*/botocore/data/route53/*"
          - "*/botocore/data/route53domains/*"
          - "*/botocore/data/route53resolver/*"
          # - '*/botocore/data/s3/*'
          # - '*/botocore/data/s3control/*'
          - "*/botocore/data/sagemaker/*"
          - "*/botocore/data/sagemaker-a2i-runtime/*"
          - "*/botocore/data/sagemaker-runtime/*"
          - "*/botocore/data/savingsplans/*"
          - "*/botocore/data/schemas/*"
          - "*/botocore/data/sdb/*"
          - '*/botocore/data/secretsmanager/*'
          - "*/botocore/data/securityhub/*"
          - "*/botocore/data/serverlessrepo/*"
          - "*/botocore/data/servicecatalog/*"
          - "*/botocore/data/servicediscovery/*"
          - "*/botocore/data/service-quotas/*"
          - "*/botocore/data/ses/*"
          - "*/botocore/data/sesv2/*"
          - "*/botocore/data/shield/*"
          - "*/botocore/data/signer/*"
          - "*/botocore/data/sms/*"
          - "*/botocore/data/sms-voice/*"
          - "*/botocore/data/snowball/*"
          - "*/botocore/data/sns/*"
          - "*/botocore/data/sqs/*"
          - '*/botocore/data/ssm/*'
          - "*/botocore/data/sso/*"
          - "*/botocore/data/sso-oidc/*"
          - "*/botocore/data/stepfunctions/*"
          - "*/botocore/data/storagegateway/*"
          - "*/botocore/data/sts/*"
          - "*/botocore/data/support/*"
          - "*/botocore/data/swf/*"
          - "*/botocore/data/textract/*"
          - "*/botocore/data/transcribe/*"
          - "*/botocore/data/transfer/*"
          - "*/botocore/data/translate/*"
          - "*/botocore/data/waf/*"
          - "*/botocore/data/waf-regional/*"
          - "*/botocore/data/wafv2/*"
          - "*/botocore/data/workdocs/*"
          - "*/botocore/data/worklink/*"
          - "*/botocore/data/workmail/*"
          - "*/botocore/data/workmailmessageflow/*"
          - "*/botocore/data/workspaces/*"
          - "*/botocore/data/xray/*"


